---
rappers:
    - name: Black Chill
    - name: \"Boo\" Sledge
      url:  http://youtu.be/1AzDWw40oDs?t=2m43s
    - name: Draytoxic
    - name: Gillie Da Kid
      url:  https://www.youtube.com/watch?v=iQYz6d-Bbpg
    - name: Lid Bux
    - name: Melo
    - name: Metro Boomin
      url:  https://www.youtube.com/watch?v=8ENpRYyoQ1M
    - name: Rug (Batcave Studio)
      url:  http://jumpphilly.com/2013/09/19/batcave-studio-underground-leaders/
    - name: Sonny Digital
      url:  https://www.youtube.com/watch?v=5cn_fdCkZlc
    - name: Star B
    - name: Tamba Hali
      url:  https://en.wikipedia.org/wiki/Tamba_Hali
    - name: \"Tank\" Tyler
      url:  https://en.wikipedia.org/wiki/Tank_Tyler
bands:
    - buckethead
    - galactic
    - ivan neville's dumpstaphunk
    - jacob fred jazz odyssey
    - mountain sprout
    - railroad earth
    - secret chiefs 3
    - shearing pinx
    - son volt
    - the avett brothers
    - this is my condition
    - trombone shorty
    - yonder mountain string band
...
